### ISSUE TITLE
Error no JSON object could be decoded

### ISSUE THREAD

**Issue by edrickchu** [itsnbyim/InstAnalytics#1]
Hey IM!

Thanks for making this script. It looks simple, effective, and super useful! I just wanted to reach out because I'm having some trouble getting the script to work.

I've set the path for phantomjs and I've run the script some times, but keep on getting this error message:

2016-04-13 Error No JSON object could be decoded

It's difficult to work on this because it doesn't specify the issue or which line the problem with the code is in. Is there any chance you might be able to help me with this? I think this tool could be very useful to me. Please let me know. Thanks!

Best,
Edrick

**Comment by hiimim** [comment]
Hello Edrick,

Thank you for your message. Actually Instagram has done some modifications in their pages' HTML structure. That caused me errors too!

I just fully update the web scraping part and it works perfectly well again! 🤓💪
Here's the output I had a few minutes ago: https://gist.github.com/helloitsim/c3a6ce83e302a1279398b896c1c36ccb

IM

**Comment by edrickchu** [comment]
Hey IM,

Thanks! I look forward to checking out this script.

Just another question, I was wondering if it's possible for me to:
1. Change the checking frequency from once every 24 hours to every hour
2. Change the time it checks from 11pm to 10:45am

Please let me know if you have any idea of where I can do this as I'm just learning python and Selenium. 

Cheers, keep up the awesome work! :)

Edrick

**Comment by hiimim** [comment]
Nothing difficult :)
1. **Change the checking frequency from once every 24 hours to every hour:** Remove line 170 (          `time.sleep(82800) # Sleep for 23 hours`)
2. **Change the time it checks from 11pm to 10:45am:**
   Change line 166 to `if datetime.now().hour == 10 and datetime.now().minute == 45`

IM
